stages:
  - build
  - deploy

variables:
  IMAGE_NAME_API: "${CI_REGISTRY_IMAGE}"
  IMAGE_TAG_RELEASE: "latest"

image: docker:cli
before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build . -t "${IMAGE_NAME_API}:${IMAGE_TAG_RELEASE}"
    - docker push "${IMAGE_NAME_API}:${IMAGE_TAG_RELEASE}"
  tags:
    - build

  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"

deploy:
  stage: deploy
  when: manual
  trigger:
    project: zoo-nsk/deploy
    branch: main

  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"

